### ISSUE TITLE
Use on client side

### ISSUE THREAD

**Issue by nithinkashyapn** [srchulo/jQuery-Facets#2]
Hey,

This is an awesome library. I recently stumbled upon this repo when I was going through SO and also saw a demo [here](http://demo.srchulo.com/jquery/jquery_facets/index.php). Can you let me know what changes needs to be done in-order to make it work completely on the client-side? I'm planning to use this in a static site.

Thanks!

**Comment by srchulo** [comment]
Hey @nithinkashyapn , this documentation should help you get setup:

http://srchulo.com/jquery_plugins/jquery_facets.html
